version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/storybook/todoList
    steps:
      - checkout:
          path: ~/storybook
      - run: 
          name: Datasetup
          command: npm install

  test:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/storybook/todoList
    steps:
      - checkout:
          path: ~/storybook
      - run: 
          name: Datasetup
          command: npm install
      - run:
          name: test
          command: npm run test:unit

workflows:
  version: 2.1
  setup_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
